---
title: "HW04-121090230-蒋飞弘"
author: "Feihong Jiang_121090230"
date: "2024/11/11"
output: html_document
---
# Q1

## a. Constrained GLS Regression
```{r}
pc = read.csv('D:/2025 Term 1/FIN4120 BY me/HW4/price_ttm.csv')
colnames(pc) = c("price","ttm")
pc$price = pc$price/100
maturity = pc$ttm

# Step 1
range1 = c(0,3)
range2 = c(3,10)
range3 = c(10,30)
nspline = 3
range_table = data.frame(matrix(c(range1,range2,range3),nspline,byrow=T))
polyorder = 2
Z = NULL
for (x in maturity){
  z = rep(0,nspline*(polyorder+1)) 
  id = which(range_table$X2>=x)[1] 
  nonzerovalue = x^seq(0,polyorder) 
  nonzeroid = seq((id-1)*(polyorder+1)+1,id*(polyorder+1))   
  z[nonzeroid] = nonzerovalue
  Z = rbind(Z,z) 
}
Z


# Step 2
n_constraints = 1+(nspline-1)*2
C = matrix(rep(0,ncol(Z)*n_constraints),ncol(Z))   
C[,1] = c(1,0,0,0,0,0,0,0,0)    
C[,2] = c(1,3,9,-1,-3,-9,0,0,0)
C[,3] = c(0,0,0,1,10,100,-1,-10,-100)  
C[,4] = c(0,1,6,0,-1,-6,0,0,0) 
C[,5] = c(0,0,0,0,1,20,0,-1,-20)
constraint = t( matrix(append(1, rep(0, n_constraints - 1)), 1)) 
C


# Step 3
Omega = diag(maturity^2)
Omegainv = solve(Omega) 


# Step 4
beta_uncontrained = solve(t(Z) %*% Omegainv %*% Z)%*% t(Z) %*%
  Omegainv %*% matrix(as.numeric(pc[,1]),byrow=F)


# Step 5
beta_constrained = beta_uncontrained + 
  solve(t(Z) %*% Omegainv %*% Z) %*% 
  C %*% 
  solve(t(C) %*% (solve(t(Z) %*% Omegainv %*% Z)) %*% C) %*%
  (constraint - t(C) %*% beta_uncontrained)
beta_constrained


# Step 6
sim_maturity = seq(0.1,30,0.1)
Z_1 = NULL
for (x in sim_maturity){
  z_1 = rep(0,nspline*(polyorder+1))
  id = which(range_table$X2>=x)[1]
  nonzerovalue = x^seq(0,polyorder)
  nonzeroid = seq((id-1)*(polyorder+1)+1,id*(polyorder+1))
  z_1[nonzeroid] = nonzerovalue
  Z_1 = rbind(Z_1,z_1)
}
discount_factor = Z_1 %*% beta_constrained
discount_factor = as.numeric(discount_factor)
yield = (1/discount_factor)^(1/sim_maturity)-1
yield_method1 = yield
plot(sim_maturity, yield, ylim=c(0,0.03), type="l", xlab="maturity", ylab="yield")
par(new=T)
lines(pc$ttm, (1/pc$price)^(1/pc$ttm)-1, type="l", col="red")


```

## b. Unstrained GLS Regression
```{r}
# Step 2
Zs = NULL
for (i in 1:polyorder){
  Zs = cbind(Zs,maturity^i)
}
Z_add = data.frame(matrix(rep(0,length(maturity)*(nspline-1)),length(maturity)))
for (i in 1:ncol(Z_add)){
  nonzeroid = which(maturity>=range_table[i+1,1])
  Z_add[,i][nonzeroid] = (maturity[nonzeroid]-range_table[i+1,1])^polyorder
}
Z = cbind(Zs,Z_add)
colnames(Z) = c("t^1","t^2","(t-3)^2_+","(t-10)^2_+")
Z = as.matrix(Z)
Z


# Step 3
beta_unconstrained = solve(t(Z) %*% Omegainv %*% Z)%*% t(Z) %*%
  Omegainv %*% matrix(as.numeric(pc$price-1),byrow=F)
beta = rbind(1,beta_unconstrained)
beta


# Step 4
Z = NULL
Z = data.frame(ones=rep(1,length(sim_maturity)))
for (i in 1:polyorder){
  Z = cbind(Z,sim_maturity^i)
}
Z_add = data.frame(matrix(rep(0,length(sim_maturity)*(nspline-1)),length(sim_maturity)))
for (i in 1:ncol(Z_add)){
  nonzeroid = which(sim_maturity>=range_table[i+1,1])
  Z_add[,i][nonzeroid] = (sim_maturity[nonzeroid]-range_table[i+1,1])^polyorder
}
Z = cbind(Z,Z_add)
Z = as.matrix(Z)
colnames(Z) = c("ones","t^1","t^2","(t-3)^2_+","(t-10)^2_+")
discount_factor = as.numeric(Z %*% beta)
yield = (1/discount_factor)^(1/sim_maturity)-1
plot(pc$ttm,(1/pc$price)^(1/pc$ttm)-1,type="l",col="red",
     xlab="maturity",ylab="yield")
lines(sim_maturity,yield,type="l",col="blue")



```


# Q2

```{r}
IRR_func = function(cf){
  P_x = round(Re(polyroot(cf)),6)
  P_x = P_x[P_x > 0]
  IRR = 1/P_x - 1
  IRR_ff = c()
  for(i in 1:length(IRR)){
    IRR_ff[i] = all(!round(IRR[i],6) == round(IRR[-i],6))
  }
  if(length(which(IRR_ff))>0){
    IRR = IRR[which(IRR_ff)]
    IRR = IRR[which.max(IRR)]
  }else{
    IRR = IRR[which.max(IRR)]
  }
  return(IRR)
}
```

## a.Price of 97.856
```{r}
round(IRR_func(cf = c(-97.856,10,10,10,10,110)),6)
```

## b.Price of 100 and 105.451
```{r}
round(IRR_func(cf = c(-100,10,10,10,10,110)),6)
round(IRR_func(cf = c(-105.451,10,10,10,10,110)),6)
```


# Q3

## a.4% and 4.5%
```{r}
R_11.25 = ((11.25-10)*0.045+(12-11.25)*0.04)/(12-10)
R_11.25
R_11.75 = ((11.75-10)*0.045+(12-11.75)*0.04)/(12-10)
R_11.75

```

## b.8.6% and 9%
```{r}
R_11.25 = ((11.25-10)*0.09+(15-11.25)*0.086)/(15-10)
R_11.25
R_11.75 = ((11.75-10)*0.09+(15-11.75)*0.086)/(15-10)
R_11.75
```


# Q4

## a.Linear Interpolation
```{r}
R_5 = ((5-4)*0.0655+(6-5)*0.062)/(6-4)
R_5
B_5 = 1/(1+R_5)^5
B_5
R_8 = ((8-7)*0.0683+(9-8)*0.0665)/(9-7)
R_8
B_8 = 1/(1+R_8)^8
B_8
```

## b.Approximation Function
```{r}
pc = cbind(c(0.95238,0.89845,0.84200,0.78614,0.68341,0.63720,0.55177,0.51312),
           c(1,2,3,4,6,7,9,10))
pc = as.data.frame(pc)
colnames(pc) = c('price','ttm')
maturity = pc$ttm

# Step 1
range1 = c(0,10)
nspline = 1
range_table = data.frame(matrix(c(range1),nspline,byrow=T))
polyorder = 3
Z = NULL
for (x in maturity){
  z = rep(0,nspline*(polyorder+1)) 
  value = x^seq(0,polyorder) 
  z = value
  Z = rbind(Z,z) 
}


# Step 2
n_constraints = 1+(nspline-1)*3
C = matrix(rep(0,ncol(Z)*n_constraints),ncol(Z))   
C[,1] = c(1,0,0,0)    
constraint = t( matrix(append(1, rep(0, n_constraints - 1)), 1)) 


# Step 3
Omega = diag(maturity^2)
Omegainv = solve(Omega) 


# Step 4
beta_uncontrained = solve(t(Z) %*% Omegainv %*% Z)%*% t(Z) %*%
  Omegainv %*% matrix(as.numeric(pc[,1]),byrow=F)


# Step 5
beta_constrained = beta_uncontrained + 
  solve(t(Z) %*% Omegainv %*% Z) %*% 
  C %*% 
  solve(t(C) %*% (solve(t(Z) %*% Omegainv %*% Z)) %*% C) %*%
  (constraint - t(C) %*% beta_uncontrained)
beta_constrained


# Step 6
B_5 = beta_constrained[1,1]+beta_constrained[2,1]*5+beta_constrained[3,1]*25+beta_constrained[4,1]*125
B_5
R_5 = (1/B_5)^(1/5)-1
R_5
B_8 = beta_constrained[1,1]+beta_constrained[2,1]*8+beta_constrained[3,1]*64+beta_constrained[4,1]*512
B_8
R_8 = (1/B_8)^(1/8)-1
R_8

```

